### ISSUE TITLE
Allow hardcoded choices or numeric ranges for commands.

### ISSUE THREAD

**Issue by hiway** [hiway/octoclaus#3]
We have no way to provide an option, such as saying ping 4 times instead of default 1. The only option is to create multiple commands each with a different set of options - it is useful when the underlying commands take drastically different actions based on the options; however for similar commands, there should be a better way.

Proposed solution:
```yaml
---
- name: "Ping variable count"
  desc: "Change ping counter."
  raw: "ping -c {{count}} 8.8.8.8"
  vars: 
    count: 
      type: number
      min: 1
      max: 10

- name: "Ping variable count and target"
  desc: "Change ping counter and target."
  raw: "ping -c {{count}} {{target}}"
  vars: 
    count: 
      type: number
      input: slider
      min: 1
      step: 3
      max: 30
    target: 
      type: text
      choices:
        - "8.8.8.8"
        - "example.com"
        - "192.168.1.1"
```

Which should display the appropriate input widget based on the presence and values of keys: `type`, `input` and `choices`. These two input methods should be sufficient for many use-cases, other methods may be explored when needed.
